version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Aponta para o nome do serviço do container postgres na rede interna do Docker
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ecommerce_db;Username=postgres;Password=postgres
    ports:
      - "5080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: